# Generated by Django 4.2.5 on 2023-09-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='num_available',
        ),
    ]
