# Generated by Django 4.2.5 on 2023-09-12 16:21

from django.db import migrations


def raise_salary(apps, schema_editor):
    Server = apps.get_model("restaurant", "Server")
    for server in Server.objects.all():
        server.salary = server.salary * 1.1
        server.save()


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_item_is_available_order_item_alter_table_number_and_more"),
    ]

    operations = [migrations.RunPython(raise_salary)]
